# Generated by Django 2.1.7 on 2019-02-19 22:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', django.contrib.postgres.fields.jsonb.JSONField()),
                ('title', django.contrib.postgres.fields.jsonb.JSONField()),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('votes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
