# Generated by Django 2.1.7 on 2019-03-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20190318_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=140),
        ),
    ]
