# Generated by Django 2.1.7 on 2019-04-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20190329_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
