# Generated by Django 2.1.7 on 2019-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20190402_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None/no-img.jpg', upload_to='post_image'),
        ),
    ]
