# Generated by Django 2.1.7 on 2019-03-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20190318_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='viewers',
            new_name='visibleTo',
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FOAF', 'FOAF'), ('Private', 'Private'), ('SERVERONLY', 'SERVERONLY'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=10),
        ),
    ]
