# Generated by Django 2.1.7 on 2019-04-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20190408_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='published',
        ),
    ]
