# Generated by Django 2.1.7 on 2019-03-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20190321_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='_visibleTo', to='Authors.Author'),
        ),
    ]
