# Generated by Django 2.1.7 on 2019-04-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20190408_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://newpee.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://newpee.herokuapp.com/'),
        ),
    ]
