# Generated by Django 2.1.7 on 2019-03-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20190321_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, to='Authors.Author'),
        ),
    ]
