# Generated by Django 2.1.7 on 2019-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20190321_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.TextField(default='text/plain'),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
