# Generated by Django 2.1.7 on 2019-04-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20190408_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='displayName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
