# Generated by Django 2.1.7 on 2019-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
