# Generated by Django 2.1.7 on 2019-03-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='posts',
            new_name='posts_created',
        ),
    ]
