# Generated by Django 2.1.7 on 2019-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
    ]
