# Generated by Django 2.1.7 on 2019-03-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_auto_20190329_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='picture',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
