# Generated by Django 2.1.7 on 2019-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_author_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='isAuthorized',
            field=models.BooleanField(default=False),
        ),
    ]
