# Generated by Django 2.1.7 on 2019-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_auto_20190303_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_followers', to='Authors.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_following', to='Authors.Author'),
        ),
    ]
