# Generated by Django 2.1.7 on 2019-04-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0003_auto_20190404_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://newpee.herokuapp.com/'),
        ),
    ]
