# Generated by Django 2.1.7 on 2019-03-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0003_auto_20190331_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='NewPee.png', upload_to='profile_image'),
        ),
    ]
