# Generated by Django 2.1.7 on 2019-04-01 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('host', models.URLField(max_length=1000, unique=True)),
                ('author_endpoint', models.URLField(max_length=1000, unique=True)),
                ('posts_endpoint', models.URLField(max_length=1000, unique=True)),
                ('username', models.CharField(default='testuser', max_length=140)),
                ('password', models.CharField(default='test_pass', max_length=140)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
