# Generated by Django 2.1.7 on 2019-03-29 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('host', models.URLField(unique=True)),
                ('author_endpoint', models.URLField(unique=True)),
                ('posts_endpoint', models.URLField(unique=True)),
            ],
        ),
    ]
