# Generated by Django 2.1.7 on 2019-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='friend_endpoint',
            field=models.URLField(default='api/friends', max_length=1000, unique=True),
        ),
    ]
