# Generated by Django 2.1.7 on 2019-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default='test_pass', max_length=140),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(default='testuser', max_length=140),
        ),
        migrations.AlterField(
            model_name='server',
            name='author_endpoint',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='server',
            name='posts_endpoint',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
